#!/bin/bash

ip_chngr(){

    LR='\033[1;31m'
    LG='\033[1;32m'
    LY='\033[1;33m'
    LC='\033[1;36m'
    LW='\033[1;37m'
    NC='\033[0m'

id=$(users | awk '{print $1}')
echo -e "${LG}[+]${LG}" "${LW}Starting Proxy service...${LW}" 
sudo service tor start
sleep 2
echo -e "${LG}[+]${LG}" "${LW}SafeguardDen now enabled for this session${LW}" 
echo ""
sleep 1
echo -e "${LG}[+]${LG}" "${LW}All Traffic going through SafeguardDen Proxy Server \n${LW}" 
mkdir -p /usr/share/SafeguardDen/output
echo  -e "Usage: 
          Enter a command : firefox
          Enter a command : curl https://check.torproject.org/ 
          Enter a command : Any command "
echo ""
echo "Save output Automatically"
echo ""
firefoxx=$(sudo -u $id pgrep -x firefox > /dev/null)
dir="/usr/share/SafeguardDen/output"
while true; do
    read -p "Enter a command (or 'exit' to quit): " cmd

    if [[ $cmd == "exit" ]]; then
        break
    elif [[ $cmd == "firefox" ]]; then
          if firefoxx; then
                echo -e "${LR}[-]${LR}" "${LR}Please close Firefox before running the command.${LR}" 

          else
                sudo -u $id xterm  -T "SafeguardDen Proxy Window" -e  "proxychains firefox https://check.torproject.org/"
          fi
    elif [[ $cmd == "curl"* ]]; then

            output_file="$dir/$(date +%Y-%m-%d_%H-%M)_curl_output.txt"
            eval "proxychains $cmd" > "$output_file" 2>&1
            sleep 2
            echo -e "${LY}[+]${LY}" "${LW}Output saved to: ${output_file}${LW}\n"

     else 
        output_file="$dir/$(date +%Y-%m-%d_%H-%M)_output.txt"
            eval "proxychains $cmd" > "$output_file" 2>&1
            echo -e "${LY}[+]${LY}" "${LW}Output saved to: ${output_file}${LW}\n"

    fi
    sudo -u kali xterm  -T "SafeguardDen Proxy Window" -e  "proxychains $cmd" 2>/dev/null
  
    
done

echo -e "${LR}[+]${LR}" "${LW}Stopping SafeguardDen Proxy service...${LW}" 
echo ""
sudo service tor stop


}
ip_chngr


