#!/bin/bash

ip_chngr(){


    LR='\033[1;31m'
    LG='\033[1;32m'
    LY='\033[1;33m'
    LC='\033[1;36m'
    LW='\033[1;37m'
    NC='\033[0m'

progreSh() {
    
    SEC=`echo "Progress"`
    PRC=`printf "%.0f" ${1}`
    SHW=`printf "%3d\n" ${PRC}`
    LNE=`printf "%.0f" $((${PRC}/2))`
    LRR=`printf "%.0f" $((${PRC}/2-12))`; if [ ${LRR} -le 0 ]; then LRR=0; fi;
    LYY=`printf "%.0f" $((${PRC}/2-24))`; if [ ${LYY} -le 0 ]; then LYY=0; fi;
    LCC=`printf "%.0f" $((${PRC}/2-36))`; if [ ${LCC} -le 0 ]; then LCC=0; fi;
    LGG=`printf "%.0f" $((${PRC}/2-48))`; if [ ${LGG} -le 0 ]; then LGG=0; fi;
    LRR_=""
    LYY_=""
    LCC_=""
    LGG_=""
    for ((i=1;i<=13;i++))
    do
        DOTS=""; for ((ii=${i};ii<13;ii++)); do DOTS="${DOTS}."; done
        if [ ${i} -le ${LNE} ]; then LRR_="${LRR_}#"; else LRR_="${LRR_}."; fi
        echo -ne "  ${LW}${SEC}  ${LR}${LRR_}${DOTS}${LY}............${LC}............${LG}............ ${SHW}%${NC}\r"
        if [ ${LNE} -ge 1 ]; then sleep .05; fi
    done
    for ((i=14;i<=25;i++))
    do
        DOTS=""; for ((ii=${i};ii<25;ii++)); do DOTS="${DOTS}."; done
        if [ ${i} -le ${LNE} ]; then LYY_="${LYY_}#"; else LYY_="${LYY_}."; fi
        echo -ne "  ${LW}${SEC}  ${LR}${LRR_}${LY}${LYY_}${DOTS}${LC}............${LG}............ ${SHW}%${NC}\r"
        if [ ${LNE} -ge 14 ]; then sleep .05; fi
    done
    for ((i=26;i<=37;i++))
    do
        DOTS=""; for ((ii=${i};ii<37;ii++)); do DOTS="${DOTS}."; done
        if [ ${i} -le ${LNE} ]; then LCC_="${LCC_}#"; else LCC_="${LCC_}."; fi
        echo -ne "  ${LW}${SEC}  ${LR}${LRR_}${LY}${LYY_}${LC}${LCC_}${DOTS}${LG}............ ${SHW}%${NC}\r"
        if [ ${LNE} -ge 26 ]; then sleep .05; fi
    done
    for ((i=38;i<=49;i++))
    do
        DOTS=""; for ((ii=${i};ii<49;ii++)); do DOTS="${DOTS}."; done
        if [ ${i} -le ${LNE} ]; then LGG_="${LGG_}#"; else LGG_="${LGG_}."; fi
        echo -ne "  ${LW}${SEC}  ${LR}${LRR_}${LY}${LYY_}${LC}${LCC_}${LG}${LGG_}${DOTS} ${SHW}%${NC}\r"
        if [ ${LNE} -ge 38 ]; then sleep .05; fi
    done
}

if ip addr show | grep -q "10.0.2."; then
  # Using NAT, so generate random IP in 10.10.x.x range
  ipaddr="10.10.$((RANDOM % 256)).$((RANDOM % 256))"
else
  # Using bridge, so generate random IP in 192.168.x.x range
  ipaddr="192.168.$((RANDOM % 256)).$((RANDOM % 256))"
fi

echo -n "Enter Your Interface : "
read interface
echo -e ${LR}"\nOld   : "${LR}${LR}"[ "${LR} ${LW}`ip addr show $interface | awk '/inet / {gsub(/\/.*/, "", $2); print $2; exit}'`${LW}${LR}" ] "${LR}
echo -e "${LC}[+]${LC}" "${LW} Genrating Ip Adress for $interface...${LW}"
sudo ip link set $interface down
sleep 2
sudo ip addr add $ipaddr dev $interface
sleep 2
sudo ip link set $interface up
sleep 2 
sudo systemctl restart networking.service
}
ip_chngr
progreSh 100 
sleep 1
echo -e ${LG}"New   : "${LG}${LR}"[ "${LR} ${LY}`ip addr show $interface | awk '/inet / {gsub(/\/.*/, "", $2); print $2; exit}'`${LY}${LR}" ] ""\n"${LR}
current_ip=$(ip addr show $interface | grep "inet " | awk '{print $2}' | cut -d "/" -f 1)
echo "$current_ip"
echo -e "${LG}[+]${LG}" "${LW}IP Adress Successfully Changed${LW}" 
echo $ipaddr